In [1]:
import numpy as np

#### Slicing of numpy arrays

### Slicing in 1 D Array

In [18]:
# One Dimensional Array
array = np.array([12,45,62,78,95,41,31])
print('Original array ::',array)
print('Printing from 1 index position :: ',array[1:])
# array[StartPosition , EndPosition]

print('Printing from index 1 to (5-1) = 4  :: ',array[1:5])

Original array :: [12 45 62 78 95 41 31]
Printing from 1 index position ::  [45 62 78 95 41 31]
Printing from index 1 to (5-1) = 4  ::  [45 62 78 95]


In [20]:
# Acces the position by skiping the steps 
array[::2]
# [12,45,62,78,95,41,31] -> [12, 62, 95, 31] skip the next element from the begining 

array([12, 62, 95, 31])

### Slicing in 2 D Array

In [13]:
array_2_d = np.array([[78,45,95,12],[45,10,20,84],[78,45,95,32]])
array_2_d

array([[78, 45, 95, 12],
       [45, 10, 20, 84],
       [78, 45, 95, 32]])

In [24]:
array_2_d[1,1:3]

array([10, 20])

In [25]:
array_2_dimensional = np.array([[78,95,12,32,10],[95,75,62,40,31],[88,81,78,61,41]])
array_2_dimensional

array([[78, 95, 12, 32, 10],
       [95, 75, 62, 40, 31],
       [88, 81, 78, 61, 41]])

In [27]:
# Accesing the last two elements
array_2_dimensional[2,3:]

array([61, 41])

In [28]:
array_2_dimensional.dtype

dtype('int32')

In [31]:
array_str = np.array([['String','Test','Five'],['Dream','Final','Demo']])

In [32]:
print(array_str.dtype)

<U6


#### Creating array defining the datatypes

In [33]:
test_array = np.array([1,2,3,4,5] , dtype='S')
print('The Array is ::',test_array)
print('The Datatypes of the array is ::',test_array.dtype)

The Array is :: [b'1' b'2' b'3' b'4' b'5']
The Datatypes of the array is :: |S1


#### Creating array with 4 bytes of integer

In [35]:
arr = np.array([7,8,9,10,5], dtype = 'i4')
print('The Given array is ::',arr)
print('DataTypes of the array is ::',arr.dtype)

The Given array is :: [ 7  8  9 10  5]
DataTypes of the array is :: int32


#### Shapes in NumPy Lib

In [36]:
array_test_1 = np.array([[1,2,3],[10,11,12]])
array_test_1.shape

(2, 3)

In [37]:
array_test_2 = np.array([ [[1,5,6],[7,8,9]], [[7,8,9],[78,42,51]] ])
array_test_2.shape

(2, 2, 3)

#### Joining Numpy Arrays

In [40]:
array_1 = np.array([45,62,31])
array_2 = np.array([78,94,42])

array_3 = np.concatenate((array_1,array_2))

print('The Third array is ::',array_3)

The Third array is :: [45 62 31 78 94 42]


#### joining 2 D Array

In [42]:
arr1 = np.array([[1,2,3],[10,11,12]])
arr2 = np.array([[77,22,33],[71,41,11]])

array_row = np.concatenate((arr1,arr2), axis = 1)
array_row

array([[ 1,  2,  3, 77, 22, 33],
       [10, 11, 12, 71, 41, 11]])

In [43]:
arr1 = np.array([[1,2,3],[10,11,12]])
arr2 = np.array([[77,22,33],[71,41,11]])

array_col = np.concatenate((arr1,arr2), axis = 0)
array_col

array([[ 1,  2,  3],
       [10, 11, 12],
       [77, 22, 33],
       [71, 41, 11]])

### Spliting the NumPy Array

#### Spliting the Array in 3 Parts

In [47]:
array_one = np.array([77,22,33,71,41,121])
new_array = np.array_split(array_one,4)
print(new_array)

[array([77, 22]), array([33, 71]), array([41]), array([121])]


### ravel & flatten
##### Converting the multidimensional array into one dimensional array.

In [51]:
array_test = np.array([ [[77,22,33],[71,41,11]],[[1,2,3],[10,11,12]] ])
print('Original Array ::',array_test)
print('Dimension of array ::',array_test.ndim)

Original Array :: [[[77 22 33]
  [71 41 11]]

 [[ 1  2  3]
  [10 11 12]]]
Dimension of array :: 3


In [56]:
new_array = array_test.ravel()
print("ravel ::",new_array)

ravel :: [77 22 33 71 41 11  1  2  3 10 11 12]


In [55]:
new_array = array_test.flatten()
print("flatten ::",new_array)

flatten :: [77 22 33 71 41 11  1  2  3 10 11 12]


#### unique Method

In [61]:
find_unique = np.array([77,22,33,71,41,11,1,2,3,10,11,12,12])
print("Given array ::",find_unique)
unique_array = np.unique(find_unique)
print("Unique array ::",unique_array)

Given array :: [77 22 33 71 41 11  1  2  3 10 11 12 12]
Unique array :: [ 1  2  3 10 11 12 22 33 41 71 77]


In [64]:
array_with_index = np.unique(find_unique, return_index = True)
print('Array With INDEX Values::',array_with_index)

Array With INDEX Values:: (array([ 1,  2,  3, 10, 11, 12, 22, 33, 41, 71, 77]), array([ 6,  7,  8,  9,  5, 11,  1,  2,  4,  3,  0], dtype=int64))


In [66]:
array_with_index = np.unique(find_unique, return_index = True, return_counts = True)
print('Array With count of repetation::',array_with_index)

Array With count of repetation:: (array([ 1,  2,  3, 10, 11, 12, 22, 33, 41, 71, 77]), array([ 6,  7,  8,  9,  5, 11,  1,  2,  4,  3,  0], dtype=int64), array([1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1], dtype=int64))


#### Deleting the Elements

In [72]:
array_delete_ex = np.array([ 1,  2,  3, 10, 11, 12, 22, 33, 41, 71, 77])
print('Given array :: ',array_delete_ex)
array_delete_ex =np.delete(array_delete_ex,[5])
print('After process ::',array_delete_ex)

Given array ::  [ 1  2  3 10 11 12 22 33 41 71 77]
After process :: [ 1  2  3 10 11 22 33 41 71 77]


#### 2 D array

In [81]:
array_two = np.array([[1.3,6.2,4.5], [1.3,6.2,4.5],[4.1,10.6,2.6]])

print(array_two)

array_modifyed = np.delete(array_two,1,axis = 0)

print()
print(array_modifyed)


[[ 1.3  6.2  4.5]
 [ 1.3  6.2  4.5]
 [ 4.1 10.6  2.6]]

[[ 1.3  6.2  4.5]
 [ 4.1 10.6  2.6]]
