In [3]:
import numpy as np

#### Use for Mathematical operations on Array or Matrix.

#### AS compare to the list the Working speed of the numpy is 50 times faster than list.

In [18]:
arr = np.array((1,2,3,4,5))
arr
print('Dimension of array',arr.ndim)

Dimension of array 1


In [15]:
arr3 = np.array(20)

In [19]:
arr3.ndim

0

### Dimension in Array

In [24]:
temp_array = np.array(45)
print('Array',temp_array)
print('Dimension of Array',temp_array.ndim)
print('type of Array',type(temp_array))

Array 45
Dimension of Array 0
type of Array <class 'numpy.ndarray'>


## 1 d Array

In [26]:
array = np.array([1,2,5,6,3,4,7,10])
array.ndim

1

## 2 d Array

In [34]:
# Syntax = two_dim_array = ([ [array1], [array2] ])
two_d_array = np.array([[1,2,3],[10,11,12]])
two_d_array

array([[ 1,  2,  3],
       [10, 11, 12]])

In [33]:
two_d_array.ndim

2

In [35]:
flot_points = np.array([[1.3,6.2,4.5],[4.1,10.6,2.6]])
flot_points

array([[ 1.3,  6.2,  4.5],
       [ 4.1, 10.6,  2.6]])

In [36]:
flot_points.ndim

2

## 3 d Array

In [37]:
three_d_array = np.array([ [[1,5,6],[7,8,9]], [[7,8,9],[78,42,51]] ])
three_d_array

array([[[ 1,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [78, 42, 51]]])

In [38]:
three_d_array.ndim

3

### We can easily find the dimension of the array using the methos 'ndim' method. with syntax  *array_name.ndim*

## Higher dimensional array

##### An Array we can have any number of dimensions.

##### When the array is created you can define the number of dimensions by using the method *ndmin*

##### Syntax : array = np.array([1,2,5,6] , ndmin = 5)

In [48]:
test_array = np.array([7,8,9,10,2] , ndmin = 5)
print('The Array is ',test_array)
print('The Dimension is',test_array.ndim)

The Array is  [[[[[ 7  8  9 10  2]]]]]
The Dimension is 5


### NumPy Array Indexing

In [50]:
arr = np.array([50,61,17,85,95,10])
print(arr[0])

50


##### Similar to list for one dimension

In [51]:
arr[5]

10

### Accesing the 2 D Array

In [55]:
array_2_d = np.array([[10,12,15,14,91] , [45,12,32,65,41]])
array_2_d

array([[10, 12, 15, 14, 91],
       [45, 12, 32, 65, 41]])

In [56]:
# For Accesing the elements use the syntax : array_name[row_position , column_position]
array_2_d[0,4]

91

In [57]:
array_2_d[1,3]

65

##### Q) From Array add 91 and 65, print the output

In [59]:
print('First Element is ',array_2_d[0,4])
print('Second Element is ',array_2_d[1,3])
print('Sum of the Elements is',array_2_d[0,4] + array_2_d[1,3])

First Element is  91
Second Element is  65
Sum of the Elements is 156


### Accesing the 3 D Array

In [62]:
array_3_d = np.array([[[10,51,61,78],[78,95,41,62]] , [[78,95,12,45],[70,80,90,10]]])
array_3_d

array([[[10, 51, 61, 78],
        [78, 95, 41, 62]],

       [[78, 95, 12, 45],
        [70, 80, 90, 10]]])

In [63]:
array_3_d.ndim

3

In [69]:
# Syntax : 3d_arrayName[First_2d_array_position, Single_d_array_postion,Column_position]
array_3_d[0,0,2]

61